# Generated by Django 6.0.2 on 2026-03-13 02:38

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercados', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
