# Generated by Django 6.0.2 on 2026-04-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercados', '0002_auto_20260313_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prioridade',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
