# Generated by Django 6.0.2 on 2026-04-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercados', '0003_categoria_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='prioridade',
            field=models.IntegerField(unique=True),
        ),
    ]
