# Generated by Django 6.0.2 on 2026-05-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchproductoffer',
            options={'verbose_name': 'Produto Ofertado', 'verbose_name_plural': 'Produtos Ofertados'},
        ),
        migrations.AlterModelOptions(
            name='branchsupermarket',
            options={'verbose_name': 'Supemercado Filial', 'verbose_name_plural': 'Supemercado Filiais'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='parentsupermarket',
            options={'verbose_name': 'Supermercado Matriz', 'verbose_name_plural': 'Supermercados Matrizes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.URLField(max_length=2083, unique=True),
        ),
        migrations.AlterField(
            model_name='parentsupermarket',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('KG', 'Quilo'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('UN', 'Unidade')], default='UN', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='branchsupermarket',
            constraint=models.UniqueConstraint(fields=('coordinates', 'parent_supermarket'), name='BranchSupermarket_coordinates_and_parent_supermarket_uniqueness'),
        ),
    ]
