# Generated by Django 6.0.2 on 2026-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_branchproductoffer_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branchsupermarket',
            name='BranchSupermarket_coordinates_and_parent_supermarket_uniqueness',
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('KG', 'KG'), ('G', 'G'), ('L', 'L'), ('ML', 'ML'), ('UN', 'UN')], default='UN', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='branchsupermarket',
            constraint=models.UniqueConstraint(fields=('coordinates', 'parent_supermarket'), name='unique_coordinates_parent_supermarket'),
        ),
    ]
